# Generated by Django 4.1.1 on 2022-09-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_product_name_product_product_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending')], default=0, max_length=255),
            preserve_default=False,
        ),
    ]
