# Generated by Django 4.1.1 on 2022-09-16 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_to_be_listed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='to_be_listed',
        ),
    ]
