# Generated by Django 4.1.1 on 2022-09-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='to_be_listed',
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending')], max_length=255),
        ),
    ]
